#This file have to be checked before each run!!!

#Define here the data repository
PathToData : "/srv/nfs/ngs-stockage/NGS_Virologie/HadrienR/DATASET/"

#Define here the data repository. Snakemake will create result files here
PathToResult : "/srv/nfs/ngs-stockage/NGS_Virologie/HadrienR/RESULTS/"

#Indicate fasta file containing reference for all genotype
PathToReference : "ref/HBV_REF.fasta"

#Params tools
TrimmParam : 500