#Defaults parameters used

#Define here the data repository
PathToData : "/srv/nfs/ngs-stockage/NGS_Virologie/HadrienR/DATASET/"

#Define here the data repository. Snakemake will create result files here
PathToResult : "/srv/nfs/ngs-stockage/NGS_Virologie/HadrienR/RESULTS/"

#Indicate fasta file containing references
PathToReference : "ref/HBV_REF.fasta"

#MULTI INFECTION THRESHOLD
multiinf : 10

##Params tools
#Nanofilt
Lmin : 1500
Lmax : 3500
headcrop : 0
tailcrop : 0

#perl
variantfrequency : 0.5
mincov : 20