################################################################################
##########################    CONFIGURATION    #################################
################################################################################

#/!\ WARNING /!\
#Be sure to always keep the following synthax for each parameters: my_param[space]:[space]my_value

################################################################################
#######################    GENERAL PARAMETERS    ###############################
################################################################################
#fastq location / Define path where the "barcode*" rep are stored
data_loc : /srv/nfs/ngs-stockage/NGS_Virologie/CCharre/MinION_HBV/RUN_GUPPYv4.2.2/DATASET_HBV/
#output location / Define path where storing analysis results 
result_loc : /srv/nfs/ngs-stockage/NGS_Virologie/CCharre/MinION_HBV/RUN_GUPPYv4.2.2/Analyse_VIRiONT/VIRiONT_MUTATION_SUBTYPE/
#custom reference file to use /  Path to fastafile containing reference sequences for blast
ref_loc : ref/HBV_subtype_V2_noPrimers.fasta
#core number / Define number of threads to use for the analysis
thread_number : 8
#memory cost in mb / Define number of threads to use for the analysis
mem_cost : 32000
#################################################################################

#################################################################################
##################    TRIMMING/FILTERING PARAMETERS    ##########################
#################################################################################
#min length for read filtering
min_length : 1000
#max length for read filtering
max_length : 3500
#average read quality for filtering
min_qual_ONT : 0
#Remove N 5' nucleotides from each filtered read 
head_trim : 21
#Remove N 3' nucleotides from each filtered read 
tail_trim : 21
#################################################################################

#################################################################################
####################    VARIANT CALLING PARAMETERS    ###########################
#################################################################################
#maximum depth for samtools mpileup
max_depth : 1000000
#base quality cutoff for samtools mpileup
basequality : 20
#################################################################################

#################################################################################
#######################    CONSENSUS PARAMETERS    ##############################
#################################################################################
#minor variant frequency
Vfreq : 0.50
#minimun coverage necessary to generate a consensus / N is called if below threshold
min_cov : 20
#################################################################################

#################################################################################
####################    MULTI-INFECTION PARAMETER    ############################
#################################################################################
#Multi infection threshold cutoff in percent / cutoff=count(Blastref_reads)/count(majoritaryBlastref_reads)*100
MI_cutoff : 20

#################################################################################
######################    HBV MUTATION RESEARCH    ##############################
#################################################################################
#set this paramater to "TRUE" will initiate optionnal mutation research for specitif HBV dataset . the "" are mandatory!
HBV_mut : "TRUE"
#location of the mutation table.
path_table : mutation_table/
#variant frequency under the threshold will be removed from filtered table. Should be between 0 and 100
freq_min : 8
#If using reference without primers, correct position in the mutation table. Could be Positive or negative.
window_pos: -21
#################################################################################
