################################################################################
##########################    CONFIGURATION    #################################
################################################################################

#/!\ WARNING /!\
#Be sure to always keep the following synthax for each parameters: my_param[space]:[space]my_value

################################################################################
#######################    GENERAL PARAMETERS    ###############################
################################################################################
#fastq location / Define path where the "barcode*" rep are stored
data_loc : /srv/nfs/ngs-stockage/NGS_Virologie/HadrienR/CARO_PIPELINE/DATA_HDV_TEST/
#output location / Define path where storing analysis results 
result_loc : /srv/nfs/ngs-stockage/NGS_Virologie/HadrienR/CARO_PIPELINE/RESULT_HDV_TEST/
#custom reference file to use /  Path to fastafile containing reference sequences for blast
ref_loc : ref/HDV_subtype_V2_noPrimers.fasta
#core number / Define number of threads to use for the analysis
thread_number : 32
#memory cost in mb / Define number of threads to use for the analysis
mem_cost : 600000
#################################################################################

#################################################################################
##################    TRIMMING/FILTERING PARAMETERS    ##########################
#################################################################################
#min length for read filtering
min_length : 500
#max length for read filtering
max_length : 2000
#average read quality for filtering
min_qual_ONT : 0
#Remove N 5' nucleotides from each filtered read 
head_trim : 23
#Remove N 3' nucleotides from each filtered read 
tail_trim : 23
#################################################################################

#################################################################################
#########################    READ CORRECTION   #0################################
#################################################################################
#enable or not read correction. Can be high time/ressource consuming depending on the following parameters.
correction : true
#average coverage of reads on the reference. /!\ This parameter significantly increase computing time if too high!
cov_correction : 1000
#corrected error rate for ONT. See the readme file for more information
error_rate : 0.105
#################################################################################

#################################################################################
####################    VARIANT CALLING PARAMETERS    ###########################
#################################################################################
#maximum depth for samtools mpileup
max_depth : 10000000
#base quality cutoff for samtools mpileup
basequality : 20
#################################################################################

#################################################################################
#######################    CONSENSUS PARAMETERS    ##############################
#################################################################################
#minor variant frequency
Vfreq : 0.50
#minimun coverage necessary to generate a consensus / N is called if below threshold
min_cov : 20
#################################################################################

#################################################################################
####################    MULTI-INFECTION PARAMETER    ############################
#################################################################################
#Multi infection threshold cutoff in percent / cutoff=count(Blastref_reads)/count(majoritaryBlastref_reads)*100
MI_cutoff : 30
#################################################################################

#################################################################################
######################    HBV MUTATION RESEARCH    ##############################
#################################################################################
#set this paramater to "TRUE" will initiate optionnal mutation research for specitif HBV dataset.
HBV_mut : FALSE
#location of the mutation table.
path_table : mutation_table/
#variant frequency under the threshold will be removed from filtered table. Should be between 0 and 100
freq_min : 8
#If using reference without primers, correct position in the mutation table. Could be Positive or negative.
window_pos: -21
#################################################################################
